src/app/client/package.json, src/app/client/src/app/modules/content-search/components/page-section/page-section.component.html, src/app/client/src/app/modules/content-search/components/page-section/page-section.component.ts, src/app/client/src/app/modules/core/components/main-footer/main-footer.component.html, src/app/client/src/app/modules/dial-code-search/components/dial-code/dial-code.component.html, src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.ts, src/app/client/src/app/modules/search/components/home-search/home-search.component.ts
=> #FP-I85: added translation to label

src/app/client/src/app/plugins/profile/components/profile-page/profile-page.component.html, src/app/client/src/app/plugins/profile/components/profile-page/profile-page.component.ts
=> #FP-I85: Added refresh component logic

src/app/client/package.json, src/app/client/src/app/modules/shared/services/config/app.config.json, src/app/client/yarn.lock
=> #FP-I86: updated config

src/app/client/package.json
=> FP-I86: Upgraded package version

src/app/client/src/app/modules/content-search/components/page-section/page-section.component.html, src/app/client/src/app/modules/content-search/components/page-section/page-section.component.scss
=> FP-I73: remove slick to show courses in grid

src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.html, src/app/client/src/app/modules/learn/components/course-consumption/course-player/course-player.component.html, src/app/client/src/app/modules/learn/components/course-consumption/course-player/course-player.component.scss, src/app/client/src/app/modules/learn/components/course-consumption/course-player/course-player.component.ts
=> FP-I73: show card loader on facetSction length is 0 for home page

src/app/client/package.json, src/app/client/src/app/plugins/profile/components/profile-page/profile-page.component.ts
=> Svg 2 pdf version increment

src/app/client/package.json
=> #FP-I79: upgraded package version

src/app/Dockerfile, src/app/client/src/app/modules/learn/components/course-consumption/course-player/course-player.component.ts, src/app/controllers/certificateDownloadController.js
=> FP-I79: added command to install chromium-browser in docker

src/app/client/package.json
=> Video player package updated

src/app/client/package.json, src/app/client/src/app/modules/learn/components/course-consumption/assessment-player/assessment-player.component.html, src/app/client/src/app/modules/learn/components/course-consumption/assessment-player/assessment-player.component.ts
=> #FP-I98: Upgraded package

src/app/client/package.json
=> FP-I124: client service for editors

src/app/client/src/app/modules/learn/components/course-consumption/assessment-player/assessment-player.component.scss, src/app/client/src/app/modules/learn/components/course-consumption/course-consumption-header/course-consumption-header.component.scss, src/app/client/src/app/modules/public/module/course/components/course-consumption/public-course-consumption-page/public-course-consumption-page.component.scss
=> #FP-I129: overflow text fix in course header

src/app/client/src/app/modules/workspace/components/content-editors/content-editor/content-editor.component.ts, src/app/client/src/app/modules/workspace/components/workspacesidebar/workspacesidebar.component.html
=> #FP-I139: show collaboration options in menu

src/app/client/package.json, src/app/client/src/app/modules/workspace/components/content-editors/new-collection-editor/new-collection-editor.component.ts
=> #FP-I139: Updated package version of collection editor

src/app/client/package.json, src/app/client/src/app/modules/workspace/components/create-content/create-content.component.html, src/app/client/src/app/modules/workspace/components/upforreview-contentplayer/upforreview-contentplayer.component.html
=> FP-I139: Collection editor version updated

src/app/helpers/whitelistApis.js
=> #FP-I186: added api in URL pattern

src/app/client/src/app/modules/workspace/components/data-driven/data-driven.component.ts
=> #FP-I186: assessment create form multilingual changes

src/app/client/src/app/modules/workspace/components/skill-map-editor/skill-map-editor.component.html, src/app/client/src/app/modules/workspace/components/skill-map-editor/skill-map-editor.component.ts, src/app/client/src/app/modules/workspace/services/skill-map-tree.service.ts
=> Make use of identifier to make update term call and storing metadata inside tree

src/app/client/src/app/modules/workspace/components/create-content/create-content.component.html, src/app/client/src/app/modules/workspace/components/create-content/create-content.component.ts, src/app/helpers/whitelistApis.js
=> #FP-I186: Creation payload fix with roles issue fix

src/app/client/src/app/modules/workspace/components/create-content/create-content.component.ts, src/app/helpers/whitelistApis.js
=> Question bank

src/app/client/src/app/modules/workspace/components/content-editors/content-editor/content-editor.component.ts, src/app/client/src/app/modules/workspace/components/create-content/create-content.component.ts, src/app/client/src/app/modules/workspace/components/question-bank-list/question-bank-list.component.ts
=> #FP-I186: Navigation issue fix for creation and edit question bank

src/app/client/src/app/modules/workspace/components/content-editors/content-editor/content-editor.component.ts
=> #FP-I186: Query params overriding issue fix

src/app/client/package.json, src/app/client/src/app/modules/shared/services/config/editor.config.json, src/app/client/src/app/modules/workspace/components/content-editors/new-collection-editor/new-collection-editor.component.ts, src/app/client/src/app/modules/workspace/components/create-content/create-content.component.ts
=> Collection editor config changes

src/app/client/src/app/modules/player-helper/components/content-player-metadata/content-player-metadata.component.html, src/app/client/src/app/modules/player-helper/components/content-player-metadata/content-player-metadata.component.ts, src/app/client/src/app/modules/shared/services/config/url.config.json
=> #FP-I186: Add observable elements mapping to content player metadata

src/app/client/package.json
=> Update sunbird-collection-editor dependency to version 1.0.7

src/app/client/package.json, src/app/client/src/app/modules/workspace/components/question-bank-list/question-bank-list.component.ts
=> Updated question bank list filter payload
